# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zsmq' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zsmq

  

  platform :ios, '9.0'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'zsmqTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'zsmq-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zsmq-tvOS

  target 'zsmq-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
